USE [master]
GO

/****** Object:  Database [Calender]    Script Date: 04.02.2022 09:27:43 ******/
CREATE DATABASE [Calender]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Calender', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Calender.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Calender_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Calender_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Calender].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Calender] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Calender] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Calender] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Calender] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Calender] SET ARITHABORT OFF 
GO

ALTER DATABASE [Calender] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Calender] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Calender] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Calender] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Calender] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Calender] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Calender] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Calender] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Calender] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Calender] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Calender] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Calender] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Calender] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Calender] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Calender] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Calender] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Calender] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Calender] SET RECOVERY FULL 
GO

ALTER DATABASE [Calender] SET  MULTI_USER 
GO

ALTER DATABASE [Calender] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Calender] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Calender] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Calender] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Calender] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Calender] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Calender] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Calender] SET  READ_WRITE 
GO

